# Generated by Django 6.0.1 on 2026-01-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                (
                    "category",
                    models.CharField(
                        choices=[("Indian", "Indian Food"), ("Fast", "Fast Food")],
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
