# Generated by Django 6.0.1 on 2026-01-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_studio", "0002_fooditem_image_alter_fooditem_category_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="order",
            name="rating",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
